permalink: /blog/:categories/:title

paginate_path: "news/page:num"
paginate: 3
highlighter: rouge

deploy: false
encoding: utf-8

gems: ['jekyll-paginate']

exclude: ['*.Rmd']

page_gen:
  - data: 'associates'
    template: 'person'
    name: 'tag'
    dir: 'people'